Xin-Xins-MacBook-Air:temp xin$ python3.7 ex18.py
Traceback (most recent call last):
  File "ex18.py", line 10, in <module>
    print_two("Zed", "Shaw")
  File "ex18.py", line 3, in print_two
    print(f"arg1: {arg1}, arg2: {arg2}")
NameError: name 'arg1' is not defined
Xin-Xins-MacBook-Air:temp xin$ python3.7 ex18.py
arg1: Zed, arg2: Shaw
arg1: {arg1}, arg2: {arg2}
arg1: First!
I got nothing'.
def print_two(*args):
    arg1, arg2 = args
    print(f"arg1: {arg1}, arg2: {arg2}")
def print_two_again(arg1, arg2):
    print("arg1: {arg1}, arg2: {arg2}")
def print_one(arg1):
    print(f"arg1: {arg1}")
def print_none():
    print("I got nothing'.")
print_two("Zed", "Shaw")
print_two_again("Zed", "Shaw")
print_one("First!")
print_none()    
